# Generated by Django 2.2.2 on 2019-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.TextField(default='', max_length=255),
        ),
    ]
